<template>
  <div class="space-y-6">
    <!-- Auto-generated Joins Section -->
    <div v-if="autoGeneratedJoins.length > 0" class="space-y-3">
      <div class="flex items-center gap-2">
        <div class="p-1.5 rounded-md bg-purple-50 dark:bg-purple-950">
          <Sparkles class="h-4 w-4 text-purple-600 dark:text-purple-400" />
        </div>
        <h4 class="text-sm font-medium">Auto-generated Joins</h4>
        <Badge variant="secondary" class="text-[10px]">{{ autoGeneratedJoins.length }}</Badge>
      </div>
      <p class="text-xs text-muted-foreground">These joins were automatically created based on table relationships. You can modify them as needed.</p>
      
      <div class="space-y-3">
        <Card 
          v-for="(join, joinIndex) in autoGeneratedJoins"
          :key="'auto-' + joinIndex"
          class="p-5 hover:shadow-md transition-shadow border-purple-100 dark:border-purple-900"
        >
          <JoinEditor
            :join="join"
            :join-index="getActualIndex(join)"
            :available-tables="availableTables"
            :is-auto-generated="true"
            :is-modified="isModified(getActualIndex(join))"
            @update="updateJoins"
            @remove="removeJoin(getActualIndex(join))"
            @mark-modified="markAsUserModified(getActualIndex(join))"
          />
        </Card>
      </div>
    </div>

    <!-- Custom Joins Section -->
    <div class="space-y-3">
      <div class="flex justify-between items-center">
        <div class="flex items-center gap-2">
          <div class="p-1.5 rounded-md bg-blue-50 dark:bg-blue-950">
            <Link class="h-4 w-4 text-blue-600 dark:text-blue-400" />
          </div>
          <h4 class="text-sm font-medium">Custom Joins</h4>
          <Badge v-if="customJoins.length > 0" variant="secondary" class="text-[10px]">{{ customJoins.length }}</Badge>
        </div>
        <div class="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            @click="emit('generate-joins')"
            title="Auto-generate missing joins based on table relationships"
          >
            <Sparkles class="h-4 w-4 mr-2" />
            Generate Joins
          </Button>
          <ColumnSelector
            :available-tables="availableTables"
            button-text="Add Join"
            @select="addJoinFromColumn"
          />
        </div>
      </div>

      <div v-if="customJoins.length === 0" class="text-center py-8 border-2 border-dashed rounded-lg">
        <Link class="h-8 w-8 mx-auto text-muted-foreground mb-2" />
        <p class="text-sm text-muted-foreground">No custom joins defined</p>
        <p class="text-xs text-muted-foreground">Add custom joins for complex relationships</p>
      </div>

      <div v-else class="space-y-3">
        <Card 
          v-for="(join, joinIndex) in customJoins"
          :key="'custom-' + joinIndex"
          class="p-5 hover:shadow-md transition-shadow"
        >
          <JoinEditor
            :join="join"
            :join-index="getActualIndex(join)"
            :available-tables="availableTables"
            :is-auto-generated="false"
            :is-modified="false"
            @update="updateJoins"
            @remove="removeJoin(getActualIndex(join))"
            @mark-modified="() => {}"
          />
        </Card>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { Card } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Badge } from '~/components/ui/badge'
import { Plus, Link, Sparkles } from 'lucide-vue-next'
import JoinEditor from './JoinEditor.vue'
import ColumnSelector from '~/components/ColumnSelector.vue'

// --- Types ---
interface JoinCondition {
  left_table: string
  left_column: string
  right_table: string
  right_column: string
}

interface Join {
  name: string
  description?: string
  join_type: 'inner' | 'left' | 'right' | 'full'
  left_table: string
  right_table: string
  conditions?: JoinCondition[]
  on?: string
  alias?: string
}

interface TableSchema {
  name: string
  columns: { name: string; type: string }[]
}

interface Props {
  modelValue: Join[]
  availableTables: TableSchema[]
}

// --- Composables ---
const props = withDefaults(defineProps<Props>(), {
  modelValue: () => [],
  availableTables: () => [],
})

const emit = defineEmits<{
  'update:modelValue': [value: Join[]]
  'generate-joins': []
}>()

// --- State ---
const localJoins = ref<Join[]>([])
const autoGeneratedFlags = ref<Record<number, boolean>>({})
const modifiedFlags = ref<Record<number, boolean>>({})
const isLocalUpdate = ref(false)

// Separate auto-generated and custom joins
const autoGeneratedJoins = computed(() => {
  return localJoins.value.filter((_, index) => autoGeneratedFlags.value[index] === true)
})

const customJoins = computed(() => {
  return localJoins.value.filter((_, index) => autoGeneratedFlags.value[index] !== true)
})

watch(() => props.modelValue, (newValue) => {
  // Skip if this was triggered by our own local update
  if (isLocalUpdate.value) {
    isLocalUpdate.value = false
    return
  }
  
  const joins = JSON.parse(JSON.stringify(newValue || []))
  
  // Extract and store autogenerated flags
  joins.forEach((join: any, index: number) => {
    if (join._autogenerated !== undefined) {
      autoGeneratedFlags.value[index] = join._autogenerated
      // Remove the flag from the join object (it's internal state only)
      delete join._autogenerated
    }
  })
  
  localJoins.value = joins
}, { immediate: true, deep: true })

// --- Methods ---
const getActualIndex = (join: Join) => {
  return localJoins.value.indexOf(join)
}

const isModified = (index: number) => {
  return modifiedFlags.value[index] === true
}

const markAsUserModified = (index: number) => {
  if (autoGeneratedFlags.value[index]) {
    modifiedFlags.value[index] = true
  }
}

const updateJoins = () => {
  isLocalUpdate.value = true
  emit('update:modelValue', localJoins.value)
}

const addJoin = () => {
  const joinNumber = localJoins.value.length + 1
  localJoins.value.push({
    name: `Join ${joinNumber}`,
    join_type: 'left',
    left_table: '',
    right_table: '',
    conditions: [{
      left_table: '',
      left_column: '',
      right_table: '',
      right_column: '',
    }],
  })
  updateJoins()
}

const addJoinFromColumn = (tableName: string, column: any) => {
  // Create a join pre-filled with the selected table and column
  const joinNumber = localJoins.value.length + 1
  localJoins.value.push({
    name: `${tableName} Join`,
    join_type: 'left',
    left_table: '', // Base table - user will select
    right_table: tableName,
    conditions: [{
      left_table: '',
      left_column: '',
      right_table: tableName,
      right_column: column.name,
    }],
  })
  updateJoins()
}

const removeJoin = (index: number) => {
  localJoins.value.splice(index, 1)
  // Also remove the flags for this index
  delete autoGeneratedFlags.value[index]
  delete modifiedFlags.value[index]
  
  // Reindex flags for subsequent joins
  const newAutoFlags: Record<number, boolean> = {}
  const newModifiedFlags: Record<number, boolean> = {}
  localJoins.value.forEach((_, newIndex) => {
    const oldIndex = newIndex >= index ? newIndex + 1 : newIndex
    if (autoGeneratedFlags.value[oldIndex] !== undefined) {
      newAutoFlags[newIndex] = autoGeneratedFlags.value[oldIndex]
    }
    if (modifiedFlags.value[oldIndex] !== undefined) {
      newModifiedFlags[newIndex] = modifiedFlags.value[oldIndex]
    }
  })
  autoGeneratedFlags.value = newAutoFlags
  modifiedFlags.value = newModifiedFlags
  
  updateJoins()
}
</script>
