<template>
  <div class="space-y-5">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div class="flex items-center space-x-2">
        <div class="p-1.5 rounded-md bg-purple-50 dark:bg-purple-950">
          <Link class="h-4 w-4 text-purple-600 dark:text-purple-400" />
        </div>
        <span class="font-medium text-base">{{ localJoin.name || 'Unnamed Join' }}</span>
        <Badge 
          v-if="props.isAutoGenerated && !props.isModified"
          variant="secondary"
          class="ml-2 text-[10px] px-1.5 py-0.5"
        >
          <Sparkles class="h-3 w-3 mr-1" />
          Auto-generated
        </Badge>
        <Badge 
          v-if="props.isAutoGenerated && props.isModified"
          variant="outline"
          class="ml-2 text-[10px] px-1.5 py-0.5"
        >
          <Pencil class="h-3 w-3 mr-1" />
          Modified
        </Badge>
      </div>
      <Button 
        variant="ghost" 
        size="sm" 
        @click="emit('remove')"
        class="hover:bg-red-50 hover:text-red-600"
      >
        <X class="h-4 w-4" />
      </Button>
    </div>

    <!-- Sentence-Completion Interface -->
    <div class="space-y-3">
      <!-- Row 1: Join table [right_table] with [left_table] using [join_type] join -->
      <div class="flex items-center gap-2 flex-wrap">
        <span class="text-sm text-muted-foreground">Join table</span>
        
        <!-- Right Table Selection -->
        <Select 
          v-model="localJoin.right_table" 
          @update:model-value="handleUpdate"
        >
          <SelectTrigger class="w-auto min-w-[160px] h-9">
            <SelectValue placeholder="Select table" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem v-for="table in props.availableTables" :key="table.name" :value="table.name">
              {{ table.name }}
            </SelectItem>
          </SelectContent>
        </Select>

        <span class="text-sm text-muted-foreground">with</span>

        <!-- Left Table Selection -->
        <Select 
          v-model="localJoin.left_table" 
          @update:model-value="handleUpdate"
        >
          <SelectTrigger class="w-auto min-w-[160px] h-9">
            <SelectValue placeholder="Select table" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem v-for="table in props.availableTables" :key="table.name" :value="table.name">
              {{ table.name }}
            </SelectItem>
          </SelectContent>
        </Select>

        <span class="text-sm text-muted-foreground">using</span>

        <!-- Join Type Selection -->
        <Select 
          v-model="localJoin.join_type" 
          @update:model-value="handleUpdate"
        >
          <SelectTrigger class="w-auto min-w-[100px] h-9">
            <SelectValue placeholder="join type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="inner">INNER</SelectItem>
            <SelectItem value="left">LEFT</SelectItem>
            <SelectItem value="right">RIGHT</SelectItem>
            <SelectItem value="full">FULL</SelectItem>
          </SelectContent>
        </Select>

        <span class="text-sm text-muted-foreground">join</span>
      </div>

      <!-- Join Conditions -->
      <div class="space-y-2 pt-2">
        <div class="text-xs text-muted-foreground font-medium">Where:</div>
        
        <!-- Show conditions if not using SQL mode -->
        <div v-if="localJoin.on === undefined" class="space-y-2">
          <div 
            v-for="(condition, condIndex) in localJoin.conditions"
            :key="condIndex"
            class="flex items-center space-x-2 bg-muted/30 p-3 rounded-md flex-wrap"
          >
            <!-- Left side -->
            <Select 
              v-model="condition.left_table" 
              @update:model-value="handleUpdate"
            >
              <SelectTrigger class="w-auto min-w-[140px] h-9">
                <SelectValue placeholder="table" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="table in props.availableTables" :key="table.name" :value="table.name">
                  {{ table.name }}
                </SelectItem>
              </SelectContent>
            </Select>
            <span class="text-sm text-muted-foreground">.</span>
            <Select 
              v-model="condition.left_column" 
              @update:model-value="handleUpdate"
            >
              <SelectTrigger class="w-auto min-w-[140px] h-9">
                <SelectValue placeholder="column" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem 
                  v-for="col in getColumnsForTable(condition.left_table)"
                  :key="col.name"
                  :value="col.name"
                >{{ col.name }}</SelectItem>
              </SelectContent>
            </Select>

            <span class="text-sm text-muted-foreground font-bold">=</span>

            <!-- Right side -->
            <Select 
              v-model="condition.right_table" 
              @update:model-value="handleUpdate"
            >
              <SelectTrigger class="w-auto min-w-[140px] h-9">
                <SelectValue placeholder="table" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="table in props.availableTables" :key="table.name" :value="table.name">
                  {{ table.name }}
                </SelectItem>
              </SelectContent>
            </Select>
            <span class="text-sm text-muted-foreground">.</span>
            <Select 
              v-model="condition.right_column" 
              @update:model-value="handleUpdate"
            >
              <SelectTrigger class="w-auto min-w-[140px] h-9">
                <SelectValue placeholder="column" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem 
                  v-for="col in getColumnsForTable(condition.right_table)"
                  :key="col.name"
                  :value="col.name"
                >{{ col.name }}</SelectItem>
              </SelectContent>
            </Select>

            <Button 
              variant="ghost" 
              size="icon" 
              class="w-8 h-8 hover:bg-red-50 hover:text-red-600" 
              @click="removeCondition(condIndex)"
            >
              <X class="h-4 w-4" />
            </Button>
          </div>

          <Button 
            variant="outline" 
            size="sm" 
            class="w-full h-9"
            @click="addCondition"
          >
            <Plus class="h-3 w-3 mr-2" />
            Add Condition
          </Button>
        </div>

        <!-- SQL ON Clause mode -->
        <div v-else class="space-y-2">
          <Textarea 
            v-model="localJoin.on"
            placeholder="e.g., table1.id = table2.table1_id"
            class="font-mono text-sm resize-none"
            rows="2"
            @update:model-value="handleUpdate"
          />
        </div>

        <!-- Toggle SQL Mode -->
        <div class="flex justify-end pt-1">
          <button
            type="button"
            class="text-xs text-muted-foreground hover:text-foreground transition-colors"
            @click="toggleSqlMode"
          >
            {{ localJoin.on !== undefined ? 'Switch to Builder Mode' : 'Switch to SQL Mode' }}
          </button>
        </div>
      </div>

      <!-- Row 2: Name it as [name] -->
      <div class="flex items-center gap-2">
        <span class="text-sm text-muted-foreground">Name it as</span>
        <Input
          v-model="localJoin.name"
          placeholder="Join name"
          class="flex-1 h-9"
          @update:model-value="handleUpdate"
        />
      </div>
    </div>

    <!-- Advanced Section -->
    <div class="pt-3">
      <button 
        type="button"
        class="flex items-center justify-between w-full text-xs text-muted-foreground hover:text-foreground transition-colors group"
        @click="showAdvanced = !showAdvanced"
      >
        <span class="flex items-center gap-1.5">
          <Settings class="h-3.5 w-3.5" />
          Advanced
        </span>
        <ChevronDown :class="['h-3.5 w-3.5 transition-transform duration-200', showAdvanced && 'rotate-180']" />
      </button>

      <div 
        v-if="showAdvanced" 
        class="mt-4 space-y-4 pt-4 border-t"
      >
        <!-- Alias -->
        <div class="space-y-1.5">
          <Label class="text-xs font-medium text-muted-foreground">Alias</Label>
          <Input
            v-model="localJoin.alias"
            placeholder="Optional alias for this join"
            class="h-9"
            @update:model-value="handleUpdate"
          />
        </div>

        <!-- Description -->
        <div class="space-y-1.5">
          <Label class="text-xs font-medium text-muted-foreground">Description</Label>
          <Textarea
            v-model="localJoin.description"
            placeholder="Describe this join..."
            rows="2"
            class="resize-none"
            @update:model-value="handleUpdate"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { Badge } from '~/components/ui/badge'
import { Textarea } from '~/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select'
import { Plus, X, Link, Settings, ChevronDown, Sparkles, Pencil } from 'lucide-vue-next'

// --- Types ---
interface JoinCondition {
  left_table: string
  left_column: string
  right_table: string
  right_column: string
}

interface Join {
  name: string
  description?: string
  join_type: 'inner' | 'left' | 'right' | 'full'
  left_table: string
  right_table: string
  conditions?: JoinCondition[]
  on?: string
  alias?: string
}

interface TableSchema {
  name: string
  columns: { name: string; type: string }[]
}

interface Props {
  join: Join
  joinIndex: number
  availableTables: TableSchema[]
  isAutoGenerated: boolean
  isModified: boolean
}

// --- Composables ---
const props = defineProps<Props>()

const emit = defineEmits<{
  update: []
  remove: []
  'mark-modified': []
}>()

// --- State ---
const localJoin = ref<Join>({ ...props.join })
const showAdvanced = ref(false)

// Watch for external changes
watch(() => props.join, (newJoin) => {
  localJoin.value = { ...newJoin }
}, { deep: true })

// --- Methods ---
const handleUpdate = () => {
  // Sync local changes back to parent
  Object.assign(props.join, localJoin.value)
  
  // Mark as modified if it's auto-generated
  if (props.isAutoGenerated) {
    emit('mark-modified')
  }
  
  emit('update')
}

const getColumnsForTable = (tableName: string) => {
  if (!tableName) return []
  const table = props.availableTables.find(t => t.name === tableName)
  return table?.columns || []
}

const addCondition = () => {
  if (localJoin.value.on !== undefined) return // Don't add conditions in SQL mode

  if (!localJoin.value.conditions) {
    localJoin.value.conditions = []
  }
  localJoin.value.conditions.push({
    left_table: '',
    left_column: '',
    right_table: '',
    right_column: '',
  })
  handleUpdate()
}

const removeCondition = (condIndex: number) => {
  if (localJoin.value.conditions) {
    localJoin.value.conditions.splice(condIndex, 1)
    handleUpdate()
  }
}

const toggleSqlMode = () => {
  if (localJoin.value.on !== undefined) {
    // Switch to builder mode
    localJoin.value.on = undefined
    if (!localJoin.value.conditions || localJoin.value.conditions.length === 0) {
      localJoin.value.conditions = [{
        left_table: '',
        left_column: '',
        right_table: '',
        right_column: '',
      }]
    }
  } else {
    // Switch to SQL mode
    // Try to generate SQL from conditions
    if (localJoin.value.conditions && localJoin.value.conditions.length > 0) {
      const sqlParts = localJoin.value.conditions
        .filter(c => c.left_table && c.left_column && c.right_table && c.right_column)
        .map(c => `${c.left_table}.${c.left_column} = ${c.right_table}.${c.right_column}`)
      localJoin.value.on = sqlParts.join(' AND ') || ''
    } else {
      localJoin.value.on = ''
    }
    localJoin.value.conditions = undefined
  }
  
  handleUpdate()
}
</script>

