"""add file_storage table

Revision ID: af2631e7b647
Revises: 8bd9e9780557
Create Date: 2026-01-17 22:28:57.450822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2631e7b647'
down_revision: Union[str, None] = '8bd9e9780557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_storage_created_at'), 'file_storage', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_storage_environment_id'), 'file_storage', ['environment_id'], unique=False)
    op.create_index(op.f('ix_file_storage_id'), 'file_storage', ['id'], unique=False)
    op.create_index(op.f('ix_file_storage_name'), 'file_storage', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_storage_name'), table_name='file_storage')
    op.drop_index(op.f('ix_file_storage_id'), table_name='file_storage')
    op.drop_index(op.f('ix_file_storage_environment_id'), table_name='file_storage')
    op.drop_index(op.f('ix_file_storage_created_at'), table_name='file_storage')
    op.drop_table('file_storage')
    # ### end Alembic commands ###
