"""add env_id to data models and metrics

Revision ID: 8bd9e9780557
Revises: 450bd09cd019
Create Date: 2025-11-13 13:26:02.360463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd9e9780557'
down_revision: Union[str, None] = '450bd09cd019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add environment_id column as nullable first
    op.add_column('data_models', sa.Column('environment_id', sa.UUID(), nullable=True))
    op.add_column('metrics', sa.Column('environment_id', sa.UUID(), nullable=True))
    
    # Get the first environment ID from the environments table
    conn = op.get_bind()
    first_env = conn.execute(sa.text("SELECT id FROM environments LIMIT 1")).fetchone()
    
    if first_env:
        first_env_id = first_env[0]
        # Assign the first environment ID to all existing rows with NULL environment_id
        op.execute(sa.text(f"UPDATE data_models SET environment_id = '{first_env_id}' WHERE environment_id IS NULL"))
        op.execute(sa.text(f"UPDATE metrics SET environment_id = '{first_env_id}' WHERE environment_id IS NULL"))
    
    # Now alter columns to be NOT NULL
    op.alter_column('data_models', 'environment_id', nullable=False)
    op.alter_column('metrics', 'environment_id', nullable=False)
    
    # Create indices and foreign keys
    op.create_index(op.f('ix_data_models_environment_id'), 'data_models', ['environment_id'], unique=False)
    op.create_foreign_key(None, 'data_models', 'environments', ['environment_id'], ['id'])
    op.create_index(op.f('ix_metrics_environment_id'), 'metrics', ['environment_id'], unique=False)
    op.create_foreign_key(None, 'metrics', 'environments', ['environment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_index(op.f('ix_metrics_environment_id'), table_name='metrics')
    op.drop_column('metrics', 'environment_id')
    op.drop_constraint(None, 'data_models', type_='foreignkey')
    op.drop_index(op.f('ix_data_models_environment_id'), table_name='data_models')
    op.drop_column('data_models', 'environment_id')
    # ### end Alembic commands ###
